image: oven/bun:1

stages:
  - lint
  - test
  - build

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .next/cache/

before_script:
  - bun install --frozen-lockfile

lint:
  stage: lint
  script:
    - bun run lint

test:
  stage: test
  before_script:
    - apt-get update && apt-get install -y nodejs
    - bun install --frozen-lockfile
  script:
    - node ./node_modules/jest/bin/jest.js --ci --runInBand

build:
  stage: build
  script:
    - bun run build
